name: reddigram
description: Instagram but Reddit.

version: 1.4.1+10

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_collection: ^4.2.0
  built_value: ^6.4.0
  cached_network_image: ^1.1.1
  dio: ^2.1.2
  firebase_analytics: ^2.1.1+3
  firebase_core: ^0.3.4
  firebase_crashlytics: ^0.0.4+2
  flutter_redux: ^0.5.3
  flutter_widgets: ^0.1.6
  jaguar_jwt: ^2.1.6
  package_info: ^0.4.0+3
  photo_view: ^0.4.0
  redux: ^3.0.0
  redux_thunk: ^0.2.1
  shared_preferences: ^0.5.2
  uni_links: ^0.2.0
  url_launcher: ^5.0.2
  validators: ^2.0.0+1
  video_player: ^0.10.1+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.3.3
  built_value_generator: ^6.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/chrome_desktop_site.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico-Regular.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
